### PR TITLE
[aws][eks] Add cert-manager to cluster addons

### PR DESCRIPTION
**Pull request by The-smooth-operator**

### CODE REVIEW

**Comment by limed** [comment]
Hmm for now i guess only a singular app would use this? would this perhaps be better suited placed in the `-infra` repo instead?

**Comment by mozafrank** [comment]
Another thing just to note here, we should move away from implementing GKE and EKS support separately; when features are added to one they should be added to the other, ideally in the same PR. Unless others disagree with this approach :)

**Comment by The-smooth-operator** [comment]
> Hmm for now i guess only a singular app would use this? would this perhaps be better suited placed in the `-infra` repo instead?

yes, only a single app which will run in 2 clusters (stage and prod). However having this allows us to use it in the future.
Anyway, I'm happy moving it to <cluster>-infra repo

**Comment by The-smooth-operator** [comment]
> Another thing just to note here, we should move away from implementing GKE and EKS support separately; when features are added to one they should be added to the other, ideally in the same PR. Unless others disagree with this approach :)

@mozafrank completely agreed. 
Furthermore I though what would it take to merge the 2 different provider-aware modules under a `kubernetes-cluster` module which could be deployed both on GCP or AWS. It wold be a huge module but will help us bringing feature parity with both cloud provider. Thoughts?

**Comment by mozafrank** [comment]
@The-smooth-operator I like that idea in general, and even for the vendor-specific ones we have I can imagine we could implement wrapper modules which would just do the right thing based on what cloud you're in. That said, most public modules I see are vendor-specific, so maybe this is not the best practice. But I like it either way :)

**Comment by limed** [comment]
> > Hmm for now i guess only a singular app would use this? would this perhaps be better suited placed in the `-infra` repo instead?
> 
> yes, only a single app which will run in 2 clusters (stage and prod). However having this allows us to use it in the future.
> Anyway, I'm happy moving it to -infra repo

We should do this at the `-infra` repo level

**Comment by The-smooth-operator** [comment]
ok, closing this

**Pull request closed without merging**
