### PR TITLE
[aws][eks] simplify and document external-secrets config

### PR DESCRIPTION
**Pull request by The-smooth-operator**

### CODE REVIEW

**Comment by The-smooth-operator** [comment]
Based on several feedback, I'm trying to make using the kubernetes-external-secrets` addon easier and documenting it

**Comment by mozafrank** [comment]
Does the doc added here apply to GCP as well?

**Comment by The-smooth-operator** [comment]
> Does the doc added here apply to GCP as well?

I'm not sure. I'm not familiar with how secrets are structured on GCP (if can be namespaced by prefix like in AWS) and how the policies/service account roles are defined. Will research about it

**Comment by limed** [comment]
> Does the doc added here apply to GCP as well?

For GCP according to my understanding is you can't path the same way you do with AWS, in AWS you can create the secret with what looks like a path and make the role that is fetching the secrets access to only that resource

In GCP land in theory I suppose you can set a condition to the role but I don't know how that would look like specifically for secrets nor do I know if secrets support it the same way

**Comment by The-smooth-operator** [comment]
@mozafrank @limed I removed the word GCP in the docs, is there something else do you guy want me to do here?

**Pull request merged**
