### PR TITLE
Se 2169

### PR DESCRIPTION
**Pull request by cmharlow**

### CODE REVIEW

**Comment by duallain** [comment]
when I set the external secrets to a list -- 

```
❯ git diff
diff --git a/terraform/stage.tf b/terraform/stage.tf
index d6e3b26..39d8d17 100644
--- a/terraform/stage.tf
+++ b/terraform/stage.tf
@@ -59,7 +59,7 @@ module "rds-ctms-stage" {
 }

 module "eks-ctms-stage" {
-  source           = "github.com/mozilla-it/terraform-modules//aws/eks?ref=2"
+  source           = "github.com/mozilla-it/terraform-modules//aws/eks?ref=SE-2169"
   cluster_name     = "ctms-stage"
   cluster_version  = "1.19"
   vpc_id           = module.info.vpc_id
@@ -73,7 +73,7 @@ module "eks-ctms-stage" {
   map_roles = local.stage_additional_roles

   external_secrets_settings = {
-    "secrets_path" = "/ess/*/stage*"
+    "secrets_path" = ["/ess/*/stage*", "test"]
   }

   flux_settings = {
   ```

I get this error -- 

```
Error: Incorrect attribute value type

  on .terraform/modules/eks-ctms-stage/aws/eks/helm.tf line 156, in resource "helm_release" "kubernetes_external_secrets":
 156:       value = item.value

Inappropriate value for attribute "value": string required.

Releasing state lock. This may take a few moments...
```

**Comment by cmharlow** [comment]
this looks like it needs a string for the helm chart values actually, not the paths. will take another look in a minute

**Comment by cmharlow** [comment]
@duallain so we don't actually use `secrets_path` in the helm chart - its not a Values option there, i believe the authors of this module just stuck secrets_path in that external_secrets_settings bc it was an easy place to group module variables & helm chart variables.

as such, i'm thinking:
1. remove secrets_path from config map passed to external_secrets helm chart values;
2. just force secrets_path to a string when passed through. this route might be safer since to use secrets_path with a list or string type, we have to remove the type map(string) anyways.

thoughts?

**Comment by duallain** [comment]
> @duallain so we don't actually use `secrets_path` in the helm chart - its not a Values option there, i believe the authors of this module just stuck secrets_path in that external_secrets_settings bc it was an easy place to group module variables & helm chart variables.
> 
> as such, i'm thinking:
> 
>     1. remove secrets_path from config map passed to external_secrets helm chart values;
> 
>     2. just force secrets_path to a string when passed through. this route might be safer since to use secrets_path with a list or string type, we have to remove the type map(string) anyways.
> 
> 
> thoughts?

That makes sense, we probably only need the paths to get the iam roles created with the correct permissions.  It feels ever so slightly better to strip the attribute out (1), but your two options are so close as that whichever one is easier is quite fine.

**Pull request closed without merging**
