### PR TITLE
Upgrade module to terraform 0.12 keeping compatibility with Terraform…

### PR DESCRIPTION
**Pull request by The-smooth-operator**
… 0.11

### CODE REVIEW

**Comment by The-smooth-operator** [comment]
@limed I've tested this with Terraform 0.11 and works as expected. Of course,  if this was used somewhere it needs to point to the commit id, but you just merge it yesterday so I don't think nothing is point here yet.

**Comment by limed** [comment]
I would actually rebase your branch against master as this has been moved to the `aws` subdirectory.

**Comment by The-smooth-operator** [comment]
> I would actually rebase your branch against master as this has been moved to the `aws` subdirectory.
:'(

**Comment by The-smooth-operator** [comment]
@limed done! I'm merging now

**Pull request merged**
